language: rust

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

cache:
    directories:
        - /home/travis/.cargo

before_cache:
    - rm -rf /home/travis/.cargo/registry

before_script:
    - rustup component add rustfmt

script:
    - cargo fmt --all -- --check
    - cargo build --all
    - cargo test --all

notifications:
    email: false
