[package]
name = "dht"
version = "0.1.0"
authors = ["bene"]

[dependencies]
base64 = "0.9.2"
bigint = "4.4.0"
byteorder = "1.2.3"
clap = "2.32.0"
ring = "0.12.1"
rust-ini = "0.12.2"
threadpool = "1.7.1"
