[package]
name = "chord"
version = "0.1.0"
authors = ["bene"]
edition = "2024"

[dependencies]
primitive-types = "0.13"
byteorder = "1.3"
log = "0.4"
ring = "0.17"
rust-ini = "0.21"
stderrlog = "0.6"
structopt = "0.3"
threadpool = "1.8"
