[package]
name = "chord"
version = "0.1.0"
authors = ["bene"]
edition = "2018"

[dependencies]
primitive-types = "0.12"
byteorder = "1.3"
log = "0.4"
ring = "0.14"
rust-ini = "0.13"
stderrlog = "0.4"
structopt = "0.2"
threadpool = "1.7"
