[package]
name = "dht"
version = "0.1.0"
authors = ["bene"]

[dependencies]
bigint = "4.4.0"
byteorder = "1.2.3"
log = "0.4.3"
ring = "0.12.1"
rust-ini = "0.12.2"
stderrlog = "0.4.1"
structopt = "0.2.10"
threadpool = "1.7.1"
