[package]
name = "dht"
version = "0.1.0"
authors = ["bene"]
edition = "2018"

[dependencies]
bigint = { version = "4.4", features = ["std"] }
byteorder = "1.3"
log = "0.4"
ring = "0.14"
rust-ini = "0.13"
stderrlog = "0.4"
structopt = "0.2"
threadpool = "1.7"
